name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8:00 自动执行
  workflow_dispatch: # 允许手动点击运行

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream
    runs-on: ubuntu-latest
    if: github.repository == 'city10666/iptv-sources'

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3 # ✨ 这里已修正为官方正确全称
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: best-fan/iptv-sources
          upstream_sync_branch: main
          
          # 如果冲突，用上游覆盖（适合纯做镜像同步）
          git_pull_args: '-s recursive -X theirs'
